---
image: 'fedora'

before_script:
  - ./setup.sh

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - HARDWARE_PLATFORM=x86_64 gprbuild acc.gpr
  artifacts:
    paths:
      - bin/*
      - build/*
    expire_in: 1 week

test:
  stage: test
  script:
    - HARDWARE_PLATFORM=x86_64 ./test.sh

package:
  stage: package
  script:
    - HARDWARE_PLATFORM=x86_64
    - dnf install -y rpm-build rpmdevtools redhat-rpm-config tree
    - rpmdev-setuptree
    - pwd && tree ~/rpmbuild
    - tar -cvzf ../acc-1.0.tar.gz .
    - pwd && tree ~/rpmbuild
    - mv ../acc-1.0.tar.gz ~/rpmbuild/SOURCES/
    - tree ~/rpmbuild
    - cp dist/acc.spec ~/rpmbuild/SPECS/
    - pwd && tree ~/rpmbuild
    - pushd ~/rpmbuild/SPECS/
    - pwd && tree ~/rpmbuild
    - rpm --eval '%{build}'
    - HARDWARE_PLATFORM=x86_64 rpmbuild --define 'build /root/rpmbuild/BUILD' -v -bb acc.spec
    - pwd && tree ~/rpmbuild
    - popd
    - pwd && tree ~/rpmbuild
    - cp -rv ~/rpmbuild/RPMS/* dist/
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week
  only:
    - master

after_script:
  - echo "End CI"
